[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
description = "Solutions to the Advent of Code 2020 puzzles"
edition = "2018"

[dependencies]
lazy_static = "1.4"
permutator = "0.4"
regex = "1.4"
